### ISSUE TITLE
PHP 5.6 incompatibility?

### ISSUE THREAD

**Issue by brainless81** [davidhemphill/presenter#11]
While running PHP 5.6.30. After updating to the most recent version we received:

`PHP Parse error:  syntax error, unexpected '(' in /srv/www/vendor/hemp/presenter/helpers.php on line 14`

Why is that line not like?

`return new PresenterFactory($model, $presenter);`

**Comment by davidhemphill** [comment]
It's not like that because it wouldn't work.  :-) 

The PresenterFactory is implemented using the `__invoke` magic method, which has been available since PHP 5.3. Are you sure you're on 5.6?

**Comment by robinmalburn** [comment]
The problem isn't `__invoke` itself, but the way it's being called, i.e. ` (new PresenterFactory)($this, $presenter)`.  The PHP parser got a pretty huge overhaul in PHP 7 that made it finally able to read basic syntax like that, but in the 5.x branch that sort of invocation - instantiating in brackets and then calling a method - isn't understood by the parser, sadly.  You can see an example of the failure [here](https://3v4l.org/SUetr) - works fine in 7.x, but fails in the 5.x branch.

I'm actually doing some playing around with this library again, though, so I'd be happy to contribute a patch that fixes this.  There's a couple of little things I was going to be putting in patches/pull requests for, anyhow.

**Comment by brainless81** [comment]
thank you! well, I honestly don't see any benefit in using an magic method here but maybe i've overseen something here. Anyway, like being said, php 5.6 cannot handle this which is said since I cannot use the lib anymore.

**Comment by robinmalburn** [comment]
PR submitted that should hopefully restore the PHP 5.x compatibility and give a small performance boost when processing larger collections, too.

**Comment by brainless81** [comment]
thank you!
