### ISSUE TITLE
getModel method sometimes returns Presenter instances, not the model itself

### ISSUE THREAD

**Issue by robinmalburn** [davidhemphill/presenter#14]
When calling `$presenter->getModel()`, there are some conditions that cause the method to return an instance of a previously applied Presenter class, rather than the raw model itself.  The issue can be recreated as follows:

```php
$user = User::first();
$user = new SamplePresenter($user);
var_dump($user->getModel() instanceof User); // returns true - an instance of User is returned.
$user = new OtherPresenter($user);
var_dump($user->getModel() instanceof User); // returns false - an instance of SamplePresenter is returned, because of the way stacked presenters are handled in the constructor.
```

Having access to previous decorators through something like getModel has benefits, but without a way to get access to the original Model in a predicable way, you run into some real issues when you need to pass around a real Laravel Model, for example, when trying to pass the model into a Route Model bound view.  It becomes unreliable to do something like `route('foo', ['user' => $user->getModel()])` because that code is going to generate the correct routing logic if exactly one presenter has been applied to the model - as soon as multiple are stacked onto the model, any links built using that code will break.

I've got a patch incoming that should hopefully resolve this in a way that maintains backwards compatibility and in a fairly painless, unobtrusive manner.  The fix also adds some unit tests to help highlight the issue and cover the new code, too, so fingers crossed you'll be happy with the solution.

**Comment by davidhemphill** [comment]
Fixed by #15! Thanks for the contribution.
