### ISSUE TITLE
problem or doubt!?, sorry

### ISSUE THREAD

**Issue by karelbyte** [davidhemphill/presenter#26]
I have a doubt, but it is a problem that I have, I am using your package, very good, thanks for developing it, the detail is that I have two presenters, but in a relationship as I apply it to the result

public function getProfile (Request $ request) {
    $ data = request-> user () -> load ('Profile') -> present (ApiUserSocial :: class);
         return response () -> json ($ data, 200);
     }

How would my ApiUserProfile apply to the profile?

**Comment by davidhemphill** [comment]
Return the relationship details in your `ApiUserSocial` presenter:

```php
public function getProfileAttribute()
{
    return [
        'username' => $this->model->profile->username
    ];
}
```

**Comment by karelbyte** [comment]
being honest, I did not understand the example!

**Comment by davidhemphill** [comment]
I'm not sure exactly what you're asking. You might want to use another `Presenter` inside your `Presenter`?

```php
// ApiUserSocial
public function getProfileAttribute()
{
    return $this->model->user->present(ProfilePresenter::class);
}
```

If that's not it, I'll need more code to know what you're trying to do.

**Comment by karelbyte** [comment]
class ApiUserSocial extends Presenter
{
    protected $hidden = [

        'id', 'usersocial_id', 'password', 'remember_token', 'created_at', 'updated_at',
    ];

    public function getEmailVerifiedAtAttribute()
    {
        return !is_null($this->model->email_verified_at);
    }

    public function getProfileAttribute()
    {
        return  $this->model->profile->present(ApiUserSocialProfile::class);
    }
}

**Comment by karelbyte** [comment]
class UserSocial extends Authenticatable
{
    use HasApiTokens,  Notifiable, Presentable;

    protected $table ="users_social";

    protected $fillable = [
       'uid', 'name', 'email', 'password',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function Profile() {

        return $this->hasOne('App\Models\UserSocialProfile', 'usersocial_id', 'id');
    }
}
