### ISSUE TITLE
Argument 1 passed to Hemp\Presenter\Presenter::__construct() must be an instance of Illuminate\Database\Eloquent\Model

### ISSUE THREAD

**Issue by matthewnessworthy** [davidhemphill/presenter#34]
In v2 the `Presenter` is forcing an eloquent model. Can this change possibly be reverted to allow for alternative objects to be passed in?

My current use-case is an object generated by an Elastic Search object which shares an interface with an eloquent model, but does not inherit from the model.

**Comment by davidhemphill** [comment]
Sure! Check out [v2.0.1](https://github.com/davidhemphill/presenter/releases/tag/v2.0.1)

**Comment by matthewnessworthy** [comment]
Excellent, thanks!
