### ISSUE TITLE
The visible attributes on the Presenter wrong working

### ISSUE THREAD

**Issue by sergeyMelnikVl** [davidhemphill/presenter#37]
/**
     * @var array
     */
    public $visible = ['username', 'first_name', 'last_name', 'status'];

result 
{
    "user": {
        "id": 1,
        "phone": "00000",
        "first_name": "Test",
        "last_name": "Test last name",
        "full_name": "Test Test last name"
    }
}

**Comment by davidhemphill** [comment]
Without a way to demonstrate this definitively I'm going to have to close it. Feel free to open a new issue when you can provide a fully demonstrative example
