### ISSUE TITLE
How to paginate

### ISSUE THREAD

**Issue by fractalzombie** [davidhemphill/presenter#4]
Hot to paginate collection with presenter?

**Comment by davidhemphill** [comment]
Hi @fractalzombie! To paginate, just call `paginate` before you call `present` on the Collection.

**Comment by marianvlad** [comment]
Something like this? I have **Method render does not exist.** error.

```
$this->tenant->getActiveTenant()->models()->paginate(16)->present(ModelPresenter::class)
```

**Comment by marianvlad** [comment]
I added this in foreach, but I don't know how good is this.
```
@php $model = $model->present(\App\Presenters\ModelPresenter::class) @endphp
```

**Comment by davidhemphill** [comment]
You can do something like this:

```php
$models = Model::paginate(20);
$links = $models->links();
$models->present(ModelPresenter::class);

return view('models.index')->with([
    'model' => $model,
    'links' => $links,
]);
```

It's not ideal to have to create an intermediate variable, but it works. I'm looking into making it just as simple as the default pagination functionality.
