### ISSUE TITLE
How to clone presenter object/collection

### ISSUE THREAD

**Issue by marufmax** [davidhemphill/presenter#42]
Every time I do an operation on Presenter collection it is calling the presenter original multiple times. Not the variable I stored. 
```
$presenter = $this->model->system->present(SummaryPresenter::class);

 $total= $presenter->where('products', '!=', 0)->sum('quantity');
```

Every time there is an operation to presenter collection it is calling `$this->model->system->present(SummaryPresenter::class);` this method again. 

Which is a performance hit.  How can I store presenter collection to a variable and then do the operations?

**Comment by davidhemphill** [comment]
I'm not sure I understand the issue you're running into. Can you explain it a different way with an example?
