### ISSUE TITLE
add correct version to support laravel 9

### ISSUE THREAD

**Issue by nour-dev** [davidhemphill/presenter#58]
hi
can you add sub version like `2.1.1` for example to support laravel `9`. currently only `dev-master` support it . and some packages depend on version `2.*` and it does not support laravel `9` (checked packagist).

thank you

**Comment by davidhemphill** [comment]
I've pushed a new release to Packagist. Thanks!

**Comment by nour-dev** [comment]
@davidhemphill thank you
