### ISSUE TITLE
Incorrect Exception Handling

### ISSUE THREAD

**Issue by robinmalburn** [davidhemphill/presenter#9]
Whilst introducing a friend to this library today, they pointed out an issue I'd missed in the [magic __get method](https://github.com/davidhemphill/presenter/blob/master/src/Presenter.php#L64) with regards to [exception handling](https://github.com/davidhemphill/presenter/blob/master/src/Presenter.php#L74).

At face value, the try/catch is catching a base `Exception`, but there's no use statement in the class, so the PHP interpreter is actually going to be trying to a catch an exception from within your namespace, i.e. `Hemp\Presenter\Exception`.  Same problem with the exception you throw in response, it'll try to throw a `Hemp\Presenter\Exception`, which would then cause an error because that class doesn't exist.

I was going to submit a PR fixing the oversight, but I on thinking about it, I'm not entirely sure how I feel about that try/catch in general.  Right now, the presumed intended behaviour would swallow and obfuscate absolutely all exceptions, regardless of whether it was a PDO exception due to a problem on the model or an error in the presenter logic itself.  Personally, if I were going to submit a PR, I'd rather just remove that try/catch completely and just let nature take it's course if an error bubbles up as I think it's less likely to cause confusion and misdirection, but I wanted to raise that as a point of discussion rather than going at the class with a carving knife.

**Comment by davidhemphill** [comment]
Ah, good catch. I appreciate that perspective. I think I'm inclined to agree with you. :-) Feel free to get your knife out. If not, I'll get to it when I can. Thanks!

**Comment by robinmalburn** [comment]
Awesome, glad we agree; PR submitted :)

**Comment by davidhemphill** [comment]
Thanks!
